name: Email Reminders

on:
  schedule:
    # Run every hour at the top of the hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Email Reminders
        run: |
          echo "Triggering email reminders..."
          response=$(curl -s -w "%{http_code}" -o /tmp/response.json "https://epg-crm.vercel.app/api/reminders/check")
          
          echo "Response code: $response"
          echo "Response body:"
          cat /tmp/response.json
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Email reminders sent successfully"
          else
            echo "❌ Email reminders failed with code: $response"
            exit 1
          fi 